### ISSUE TITLE
How to run on local server

### ISSUE THREAD

**Issue by DanielLvovsky** [das-jishu/kratos#1]
Hi there!

I stumbled upon this project and I just want to explore and learn.

I am just wondering, is it possible to run this on a local server. since I am getting an error when I am running "ng start". Is there something that I need to install?

Thanks,
Daniel

**Comment by das-jishu** [comment]
Hi Daniel,

Use "**_ng serve_**" to reproduce the site on your local server. However, I should warn you that you won't be getting the exact same site since we haven't uploaded the firebase configuration files and other components (for security purposes). 

If you still want to work on this, do create a  Firebase database of your own and use the rest of our code here. Thanks for your interest!

😅

**Comment by DanielLvovsky** [comment]
Thank you for the response. Hopefully that should work.

**Comment by DanielLvovsky** [comment]
One more question:

When I use "npm install" and then "ng serve" I get an error, is there anything I need to install separately like the Angular CLI?

Thanks in advance

**Comment by das-jishu** [comment]
Yes, you would need the Angular CLI or else you won't be able to execute commands for Angular. Could you post the error here so that I can understand where the error is occurring precisely?

**Comment by DanielLvovsky** [comment]
I will run the commands again and if there will be errors I will post it here.

**Comment by DanielLvovsky** [comment]
So I ran npm install and then ng serve and here is what I got:



ERROR in src/app/services/post.service.ts:8:32 - error TS2307: Cannot find module './mailing.service'.

8 import { MailingService } from './mailing.service';
                                 ~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:30:29 - error TS2307: Cannot find module './../environments/environment'.

30 import { environment } from './../environments/environment';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:31:37 - error TS2307: Cannot find module './admin/admin-login/admin-login.component'.

31 import { AdminLoginComponent } from './admin/admin-login/admin-login.component';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:32:40 - error TS2307: Cannot find module './admin/admin-products/admin-products.component'.

32 import { AdminProductsComponent } from './admin/admin-products/admin-products.component';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:59:32 - error TS2307: Cannot find module './services/mailing.service'.

59 import { MailingService } from './services/mailing.service';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.ts:5:29 - error TS2307: Cannot find module './environments/environment'.

5 import { environment } from './environments/environment';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2020-09-20T01:53:34.056Z - Hash: 2cc916faa23f39777dba
1 unchanged chunks
chunk {firebase-auth} firebase-auth.js, firebase-auth.js.map (firebase-auth) 178 kB  [rendered]
chunk {main} main.js, main.js.map (main) 396 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 150 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.98 MB [initial] [rendered]
Time: 29013ms

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './../environments/environment' in 'C:\Users\danik\Desktop\cloakspace-master\src\app'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './admin/admin-login/admin-login.component' in 'C:\Users\danik\Desktop\cloakspace-master\src\app'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './admin/admin-products/admin-products.component' in 'C:\Users\danik\Desktop\cloakspace-master\src\app'
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './environments/environment' in 'C:\Users\danik\Desktop\cloakspace-master\src'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './services/mailing.service' in 'C:\Users\danik\Desktop\cloakspace-master\src\app'     

    ERROR in src/app/services/post.service.ts:8:32 - error TS2307: Cannot find module './mailing.service'.

    8 import { MailingService } from './mailing.service';
                                     ~~~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:30:29 - error TS2307: Cannot find module './../environments/environment'.

    30 import { environment } from './../environments/environment';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:31:37 - error TS2307: Cannot find module './admin/admin-login/admin-login.component'.

    31 import { AdminLoginComponent } from './admin/admin-login/admin-login.component';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:32:40 - error TS2307: Cannot find module './admin/admin-products/admin-products.component'.

    32 import { AdminProductsComponent } from './admin/admin-products/admin-products.component';
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:59:32 - error TS2307: Cannot find module './services/mailing.service'.

    59 import { MailingService } from './services/mailing.service';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/main.ts:5:29 - error TS2307: Cannot find module './environments/environment'.

    5 import { environment } from './environments/environment';

**Comment by das-jishu** [comment]
As I mentioned earlier, some of the components and the environment variables for Firebase database and hosting haven't been uploaded. So these files (for instance, mailing-service.ts, environment.ts) will be missing as mentioned in the error log. You need to implement them on your own. However if you would like a sneak peek of the code, leave your mail here, and I'll send you a sample.

**Comment by DanielLvovsky** [comment]
I see, well if you could provide the samples that would be great. 

Here is my email: danik2000.l@hotmail.com

Thank you

**Comment by das-jishu** [comment]
Hi, could you please recheck your email address? It says that it doesn't exist.

**Comment by DanielLvovsky** [comment]
Here try this one danlvovsky@gmail.com

**Comment by alpha037** [comment]
Hi @DanielLvovsky , do check your email. We've sent you a sample. Thank you for contacting us.
Keep learning. ✌
