### ISSUE TITLE
hi, how are you?

### ISSUE THREAD

**Issue by gdiux** [das-jishu/kratos#2]
you can provide the Mailing services
gacpdesigns@gmail.com

What database model are you using in firebase, cloud firestore or Realtime database?

thanks, i like your project.

**Comment by das-jishu** [comment]
Thanks for your interest in our project. We have relied on Firebase realtime database for our needs in this one, although Firestore is a good alternative to that. Could you provide some insight on how this helps you or your work so that we get to know more?

**Comment by gdiux** [comment]
learning :)
